# Copyright 2026 tansadio
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
import logging
import time
from urllib.parse import quote

from odoo import api, models
from odoo.exceptions import UserError

from odoo.addons.cmis.exceptions import CMISContentAlreadyExistsError
from odoo.addons.cmis_alf.alfresco_client import node_id_from_object_id

_logger = logging.getLogger(__name__)

PDF_RENDITION = "pdf"
POLL_INTERVAL = 0.5

# documents previewed from the PDF rendition generated by Alfresco
PDF_RENDITION_MIMETYPES = {
    "application/msword",
    "application/rtf",
    "application/vnd.ms-excel",
    "application/vnd.ms-powerpoint",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/csv",
    "text/rtf",
}


class CmisFolderWidget(models.AbstractModel):
    _inherit = "cmis.folder.widget"

    @api.model
    def _get_share_url(self, context, cmis_object):
        noderef = cmis_object.properties.get("alfcmis:nodeRef") or (
            f"workspace://SpacesStore/{node_id_from_object_id(cmis_object.id)}"
        )
        page = "folder-details" if cmis_object.is_folder else "document-details"
        share = context.backend.share_location.rstrip("/")
        return f"{share}/page/{page}?nodeRef={quote(noderef, safe='')}"

    @api.model
    def _serialize(self, context, cmis_object):
        values = super()._serialize(context, cmis_object)
        if cmis_object.is_document and values["mimetype"] in PDF_RENDITION_MIMETYPES:
            values["preview_rendition"] = PDF_RENDITION
        if context.backend.alfresco_share_links:
            values["share_url"] = self._get_share_url(context, cmis_object)
        return values

    @api.model
    def _wait_rendition(self, client, node_id, rendition, timeout):
        """Ask Alfresco to generate the rendition if needed and wait for it"""
        path = f"nodes/{node_id}/renditions"
        if client.request("GET", f"{path}/{rendition}").get("status") == "CREATED":
            return True
        try:
            client.request("POST", path, json={"id": rendition})
        except CMISContentAlreadyExistsError:
            _logger.debug("Rendition %s of %s already requested", rendition, node_id)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            time.sleep(POLL_INTERVAL)
            if client.request("GET", f"{path}/{rendition}").get("status") == "CREATED":
                return True
        return False

    @api.model
    def get_rendition(self, model, res_id, field_name, object_id):
        """Return the document and a streamed response of its PDF rendition"""
        context = self._get_context(model, res_id, field_name)
        document = context.get_object(object_id)
        if not document.is_document or (
            document.mime_type not in PDF_RENDITION_MIMETYPES
        ):
            raise UserError(self.env._("No preview available for %s.", document.name))
        client = context.backend.get_alfresco_client()
        node_id = node_id_from_object_id(document.id)
        timeout = context.backend.alfresco_rendition_timeout or 0
        if not self._wait_rendition(client, node_id, PDF_RENDITION, timeout):
            raise UserError(
                self.env._(
                    "The preview of %s is not ready yet, please retry later.",
                    document.name,
                )
            )
        response = client.session.request(
            "GET",
            f"{client.url}/nodes/{node_id}/renditions/{PDF_RENDITION}/content",
            params={"attachment": "false"},
            stream=True,
            timeout=client.timeout,
        )
        response.raise_for_status()
        return document, response
